### ISSUE TITLE
Suggest renaming ``predicted_proba`` to ``predicted_probability``  

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-ml#6]
I was taking a quick look at the schema and I think for consistency and better human readability, it would be useful to rename ``predicted_proba`` to ``predicted_probability``  

https://github.com/hdmf-dev/hdmf-ml/blob/d010d4c23d446effcd7f4b0bc0c6a6eeefa5155e/ml/ml_table.yaml#L102

**Comment by rly** [comment]
I agree. Fixed. Thanks
